config/routes.rb
Rails.application.routes.draw do

  namespace :admin do
    root :to => "base#index"
    resources :users do
      resources :permissions

      put "permissions", to: "permissions#set", as: "set_permissions"
    end
    resources :states do
      member do
        get :make_default
      end
    end
  end

  get 'users/new'

  get 'users/create'

  get 'users/show'

  root "projects#index"

  resources :projects do
    resources :tickets
  end

  resources :tickets do
    resources :comments
    resources :tags do
      member do
        delete :remove
      end
    end
  end

  resources :users

  resources :files

  get "/signin", to: "sessions#new"
  post "/signin", to: "sessions#create"
  delete "/signout", to: "sessions#destroy", as: "signout"









end

app/models/user.rb
class User < ActiveRecord::Base
	has_secure_password

	validates :email, presence: true

	has_many :permissions

	def to_s
		"#{email} (#{admin? ? "Admin" : "User"})"
	end
end

app/controllers/admin/users_controller.rb
class Admin::UsersController < Admin::BaseController
	before_action :set_user, only: [:show, :edit, :update, :destroy]

  def index
  	@users = User.order(:email)
  end

  def new
  	@user = User.new
  end

  def create
  	params = user_params.dup
  	params[:password_confirmation] = params[:password]
  	@user = User.new(params)

  	if @user.save
  		flash[:notice] = "User has been created."
  		redirect_to admin_users_path
  	else
  		flash[:alert] = "User has not been created."
  		render :action => "new"
  	end
  end

  def show
  end

  def edit
  end

  def update
  	params = user_params.dup
  	if params[:password].blank? 
  		params.delete(:password)
  		params.delete(:password_confirmation)
  	else 
  		params[:password_confirmation] = params[:password]
  	end

   	if @user.update(params)
  		flash[:notice] = "User has been updated."
  		redirect_to admin_users_path
  	else
  		flash[:alert] = "User has not been updated."
  		render action: "edit"
  	end
  end

  def destroy
  	if @user == current_user
  		flash[:alert] = "You cannot delete yourself."
  	else
  		@user.destroy
  		flash[:notice] = "User has been deleted."
  	end
  	redirect_to admin_users_path
  end

  private
  		def user_params
  			params.require(:user).permit(:name, :email, :password, :password_confirmation, :admin)
  		end

  		def set_user
  			@user = User.find(params[:id])
  		end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
	before_action :set_user, only: [:show, :edit, :update]
  def new
  	@user = User.new
  end

  def create
  	@user = User.new(user_params)

  	if @user.save
      session[:user_id] = @user.id 
  		flash[:notice] = "You have signed up successfully."
  		redirect_to projects_path
  	else
  		render :new
  	end
  end

  def show
  end

  def edit
  end

  def update
  	if @user.update(user_params)
  		flash[:notice] = "Profile has been updated."
  		redirect_to @user
  	else
  		flash[:alert] = "Profile has not been updated."
  		render "edit"
  	end
  end

  private
  		def set_user
  			@user = User.find(params[:id])
  		end

  		def user_params
  			params.require(:user).permit(:name, :email, :password, :password_confirmation)
  		end
end

app/helpers/admin/users_helper.rb
module Admin::UsersHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/admin/users/_form.html.erb
<%= form_for [:admin, @user] do |f| %>
	<% if @user.errors.any? %>
	<div id="error_explanation">
		<h2><%= pluralize(@user.errors.count, "error") %> prohibited this user from being saved:<h2>
			<ul>
				<% @user.errors.full_messages.each do |msg| %>
					<li><%= msg %></li>
				<% end %>
			</ul>
		</div>
	<% end %>
	<p>
		<%= f.label :name %>
		<%= f.text_field :name %>
	</p>
	<p>
		<%= f.label :email %>
		<%= f.text_field :email %>
	</p>
	<p>
		<%= f.label :password %>
		<%= f.password_field :password %>
	</p>
	<p>
		<%= f.check_box :admin %>
		<%= f.label :admin, "Is an admin?" %>
	</p>
	<%= f.submit %>
<% end %>

app/views/admin/users/edit.html.erb
<h2>Editing a user</h2>
<%= render "form" %>

app/views/admin/users/index.html.erb
<%= link_to "New User", new_admin_user_path %>
<ul id='users'>
	<% @users.each do |user| %>
		<li><%= link_to user, [:admin, user] %></li>
	<% end %>
</ul>

app/views/admin/users/new.html.erb
<h2>New User</h2>
<%= render "form" %>

app/views/admin/users/show.html.erb
<h2><%= @user %></h2>
<%= link_to "Edit User", edit_admin_user_path(@user) %>
<%= link_to "Delete User", admin_user_path(@user), method: :delete,
		data: { confirm: "Are you sure you want to delete this user?" } %>

<%= link_to "Permissions", admin_user_permissions_path(@user) %>